;(function($,window,document,undefined){var pluginName="foolSearch",defaults={maxResults:10};function FoolSearch(element,options){this.element=element;this.$element=$(element);this.options=$.extend({},defaults,options);this.init();}
FoolSearch.prototype={init:function(){this.$resultsEl=$('<div class="ticker-input-results" role="list" aria-hidden="true"></div>');this.$resultsEl.hide();this.$resultsEl.insertAfter(this.element);this.keysBound=false;var _this=this;this.$resultsEl.on('mouseover','.ticker-input-results-result',function(e){_this.handleMouseOver.call(_this,e);});this.$resultsEl.on('click','.ticker-input-results-result',function(e){_this.submitEl($(e.target).closest('.ticker-input-results-result'))});$(this.element).on('focus',function(){if(!_this.keysBound){_this.attachKeyListeners.call(_this);_this.keysBound=true;}
if(!_this.resultsShowing()){$(_this.element).val('');}});$(this.element).on('blur',function(){_this.disposeKeyListeners.call(_this);_this.keysBound=false;});$(document).on('click',function(e){if($(e.target).closest('.ticker-input-results').length===0&&e.target!==_this.element){_this.hideResults();_this.disposeKeyListeners();}});this.premiumId=null;var page_type=window.location.pathname.match(/^(.*)\/((19|20)\d\d[\/.](0[1-9]|1[012])[\/.](0[1-9]|[12][0-9]|3[01]))\/(.*)$/);if(!page_type)
{var matches=window.location.pathname.match(/^(.*)\/(\d*)\/(.*)$/);if(matches){this.premiumId=matches[2];}}},resultsShowing:function(){return this.$resultsEl.attr("aria-hidden")==="false";},attachKeyListeners:function(){var _this=this,$el=$(this.element);$el.on('propertychange input',function(){_this.handleInputChange.call(_this,$el.val());});$el.on('keydown',function(e){_this.handleKeyDown.call(_this,e)});},disposeKeyListeners:function(){var $el=$(this.element);$el.off('input');$el.off('keydown');},handleInputChange:function(q){if(q==""){this.hideResults();return;}
var _this=this;$.ajax({url:"https://www.fool.com/a/quotes/v4/instruments/search/",contentType:'application/json',dataType:"json",data:{maxResults:this.options.maxResults,apiKey:"public",domain:"fool.com",query:q},success:function(response){if(response&&response.ResultsFound){_this.showResults(response.SearchResults);}else{_this.hideResults();}}});},handleKeyDown:function(e){switch(e.which){case 13:this.submit();break;case 27:this.hideResults();break;case 37:case 38:if(this.resultsShowing()){this.moveSelectionUp();}
break;case 39:case 40:if(this.resultsShowing()){this.moveSelectionDown();}
break;case 9:this.hideResults();return;default:return;}
e.preventDefault();},handleMouseOver:function(e){var $target=$(e.target);$target.siblings('.active').removeClass('active');$target.addClass('active');},moveSelectionUp:function(){var $activeEl=this.$resultsEl.find(".active");if($activeEl.length<=0){$activeEl=this.$resultsEl.find("div.ticker-input-results-result:last-child");$activeEl.addClass("active");return;}
var $prevEl=$activeEl.prev(".ticker-input-results-result");if($prevEl.length<=0){$prevEl=this.$resultsEl.find("div.ticker-input-results-result:last-child");}
$prevEl.addClass("active");$activeEl.removeClass("active");},moveSelectionDown:function(){var $activeEl=this.$resultsEl.find(".active");if($activeEl.length<=0){$activeEl=this.$resultsEl.find("div.ticker-input-results-result:first-child");$activeEl.addClass("active");return;}
var $nextEl=$activeEl.next(".ticker-input-results-result");if($nextEl.length<=0){$nextEl=this.$resultsEl.find("div.ticker-input-results-result:first-child");}
$nextEl.addClass("active");$activeEl.removeClass("active");},showResults:function(results){var items='';for(var i=0;i<results.length;i++){var r=results[i];items+='<div class="ticker-input-results-result'+(i===0?' active':'')+'" role="listitem" aria-valuetext="'+r.Name+'" aria-hidden="false" data-instrument-id='+r.InstrumentId+'>'+'<span class="ticker-input-results-symbol">'+r.Symbol+'</span>'+'<span class="ticker-input-results-company">'+r.Name+'</span>'+'<span class="ticker-input-results-exchange">'+r.Exchange+'</span>'+'<span class="exchange-icon exchange-'+r.Exchange+'"></span>'+'</div>';}
this.$resultsEl.html(items);this.$resultsEl.show();this.$resultsEl.attr("aria-hidden","false");},hideResults:function(){this.$resultsEl.hide();this.$resultsEl.attr("aria-hidden","true");this.$resultsEl.html('');},submit:function(){this.submitEl(this.$resultsEl.find(".active"));},submitEl:function(el){this.defaultAction(el,this);},defaultAction:function(el,search){if(el.length>0){var symbol=el.find(".ticker-input-results-symbol").text();var exchange=el.find(".ticker-input-results-exchange").text();var instrumentId=el.data('instrumentId');$(this.element).val(exchange+":"+symbol);var quoteUrl="https://www.fool.com/quote/";if(this.premiumId){quoteUrl+=this.premiumId+'/';}
window.location.href=quoteUrl+instrumentId;}else{if(this.premiumId){window.location.href="https://www.fool.com/search/ "+premiumId+"/solr.aspx?q="+$(this.element).val();}
else{window.location.href="https://www.fool.com/search/solr.aspx?q="+$(this.element).val();}}}};$.fn[pluginName]=function(options){return this.each(function(){if(!$.data(this,"plugin_"+pluginName)){var searchPlugin=new FoolSearch(this,options);if(options&&options.defaultAction){searchPlugin.defaultAction=options.defaultAction;}
$.data(this,"plugin_"+pluginName,searchPlugin);}});};})(jQuery,window,document);$(document).ready(function(){$('.ticker-input-input').foolSearch();});;;(function($){function SingleTabNav(element,options){var defaults={tabSelector:"> ul > li > a"};this.element=element;this.$element=$(element);this.options=$.extend({},defaults,options);this.indexAttribute="data-pos-index";this.init();}
SingleTabNav.prototype={init:function(){var self=this;var keyActions=new KeyActions(this.$element);var tabbableSelector=this.$element.attr("data-tabbable-selector")||this.options["tabSelector"];this.$allTabbable=this.$element.find(tabbableSelector+":visible");this.$allTabbable.each(function(i,element){$(element).attr(self.indexAttribute,i);});this.focusIndex=0;this.tabbableCount=this.$allTabbable.length;this.$firstTabbable=$(this.$allTabbable[0]);this.$firstTabbable.attr("tabindex",0);this.$forcedTabbable=this.$allTabbable.filter(function(index){return index!==0;});this.$forcedTabbable.attr("tabindex",-1);this.$allTabbable.on("focus",function(){var $element=$(this);self.focusIndex=parseInt($element.attr(self.indexAttribute));self.$allTabbable.attr("aria-selected",false);$element.attr("aria-selected",true);});this.$allTabbable.on("blur",function(){$(this).attr("aria-selected",false);});keyActions.addKey("left",function(){self.focusIndex--;self.setFocusOnCurrentIndex();return false;});keyActions.addKey("right",function(){self.focusIndex++;self.setFocusOnCurrentIndex();return false;});this.$element.on('keydown',function(event){var code=event.keyCode;event.stopPropagation();return keyActions.fireKey(code);});},setFocusOnCurrentIndex:function(){var focusElement;if(this.tabbableCount<=this.focusIndex){this.focusIndex=0;}
if(this.focusIndex<0){this.focusIndex=this.tabbableCount-1;}
if(this.focusIndex===0){focusElement=this.$firstTabbable;}
else{focusElement=$(this.$forcedTabbable.get(this.focusIndex-1));}
focusElement.focus();}}
$.fn["singleTabNav"]=function(options){return this.each(function(){if(!$.data(this,"singleTabNav")){var singleTabNav=new SingleTabNav(this,options);$.data(this,"singleTabNav",singleTabNav);}});};function KeyActionDropDown(element,options){var defaults={listElementsSelector:'li a'};this.element=element;this.$element=$(element);this.options=$.extend({},defaults,options);this.init();}
KeyActionDropDown.prototype={init:function(){var self=this;var keyActions=new KeyActions(this.$element);this.listContainer=this.$element.find('ul');this.listElements=this.listContainer.find(this.options.listElementsSelector);this.isExpanded=false;this.focusIndex=0;this.$element.attr('role','button');this.$element.attr('aria-haspopup',true);this.$element.attr('aria-expanded',false);this.listContainer.attr('role','listbox');this.listElements.attr('role','option');this.$element.find('a').attr("tabindex",-2);function setFocusOnCurrentIndex(){var focusedElement;if(self.listElements.length<=self.focusIndex){self.focusIndex=0;}
if(self.focusIndex<0){self.focusIndex=self.listElements.length-1;}
self.listElements.attr("aria-selected",false);focusedElement=$(self.listElements.get(self.focusIndex));focusedElement.attr("aria-selected",true);focusedElement.focus();}
function focusTop(){self.$element.focus();}
function closeDropDown(){if(self.isExpanded){self.$element.attr('aria-expanded',false);self.listContainer.removeClass('expanded');self.isExpanded=false;self.focusIndex=0;}}
function toggleDropDown(){self.$element.attr('aria-expanded',false);self.listContainer.toggleClass('expanded');self.isExpanded=!self.isExpanded;if(self.isExpanded){self.$element.attr('aria-expanded',true);self.focusIndex=0;setFocusOnCurrentIndex();}
else{focusTop();}}
$('body').on("click",function(){closeDropDown();});this.$element.on('click',function(event){event.stopPropagation();toggleDropDown();});keyActions.addKey("enter",function(event){var focusedElement;if(self.isExpanded){focusedElement=self.listElements.get(self.focusIndex);if(focusedElement){focusedElement.click();}
closeDropDown();}
else{toggleDropDown();}});keyActions.addKey("up",function(){if(self.isExpanded){self.focusIndex--;setFocusOnCurrentIndex();return false;}
return true;});keyActions.addKey("down",function(){if(self.isExpanded){self.focusIndex++;setFocusOnCurrentIndex();return false;}
toggleDropDown();return true;});keyActions.addKey("left",function(){if(self.isExpanded){closeDropDown();}
return true;});keyActions.addKey("right",function(){if(self.isExpanded){closeDropDown();}
return true;});keyActions.addKey("escape",function(){if(self.isExpanded){closeDropDown();focusTop();return false;}
return true;});keyActions.addKey("tab",function(){if(self.isExpanded){closeDropDown();}
return true;});this.$element.on('keydown',function(event){var code=event.keyCode;return keyActions.fireKey(code);});}}
$.fn["keyActionDropDown"]=function(options){return this.each(function(){if(!$.data(this,"keyActionDropDown")){var keyActionDropDown=new KeyActionDropDown(this,options);$.data(this,"keyActionDropDown",keyActionDropDown);}});};function KeyActions($element){var keyStringMap={"tab":9,"left":37,"right":39,"down":40,"up":38,"enter":13,"escape":27,"backspace":8}
this.$element=$element;this.keyActions=[];function getCodeFromString(codeName){return keyStringMap[codeName];}
KeyActions.prototype.addKey=function(strOrCode,fn){var code=typeof strOrCode==="number"?strOrCode:getCodeFromString(strOrCode);var keyAction={key:code,action:fn};this.keyActions.push(keyAction);}
KeyActions.prototype.fireKey=function(code){var exitCode=true;this.keyActions.forEach(function(keyAction){if(keyAction.key!==code){return;}
exitCode=keyAction.action();});return exitCode;}}})(jQuery);$(document).ready(function(){$('.fool-tophat').singleTabNav();$('.js-single-tab-nav, #main-menu-nav, .top-nav').singleTabNav();$('.navigation-menu.show').singleTabNav({tabSelector:'li.nav-link'});$('div.hp-services-tabs').singleTabNav({tabSelector:'div.hp-service-tab'});$('.member-offers-filters').singleTabNav({tabSelector:'.member-offers-filter'});$('ul.dropMenu').keyActionDropDown();$('#js-navigation-menu li.nav-link').keyActionDropDown();$('input').keyup(function(e){if(e.which==40){$(this).closest('.fieldWrapper').next().find('input').focus();}else if(e.which==38){$(this).closest('.fieldWrapper').prev().find('input').focus();}});});;(function(){var ajax=new XMLHttpRequest();ajax.open("GET","https://g.foolcdn.com/misc-assets/fontawesome5_sprite.svg",true);ajax.send();ajax.onload=function(e){var parser=new DOMParser();var ajaxdoc=parser.parseFromString(ajax.responseText,"image/svg+xml");document.getElementsByTagName('body')[0].appendChild(ajaxdoc.getElementsByTagName('svg')[0]);}})();;