$('body').on('click','.related-tickers a',function(){article_num=$(this).parents('.full_article').attr("id");if(article_num.length==0){article_num=$(this).parents('.articorial').attr("id");}
Infotrack.track('Click-Sidebar-Stocks',{category:'Article-Page',label:article_num,});});$('body').on('click','.full_article .ticker a',function(){article_num=$(this).parents('.full_article').attr("id");if(article_num.length==0){article_num=$(this).parents('.articorial').attr("id");}
Infotrack.track('Click-Content-Stocks',{category:'Article-Page',label:article_num,});});$('body').on('click',".read-more-section a:not('.read-more-section.in-content a')",function(){let itemPosition=$(".read-more-section a:not('.read-more-section.in-content a')").index($(this))+1;Infotrack.track('Click-ReadMore',{category:'Article-Page',label:itemPosition,});});$('body').on('click','.read-more-articles .read-more-articles-item a',function(){Infotrack.track('Click-Main-ReadMore',{category:'Article-Page',label:$(this).text(),});});$('body').on('click','[id$="pitch"] a',function(){article_num=$(this).parents('.full_article').attr("id");if(article_num.length==0){article_num=$(this).parents('.articorial').attr("id");}
Infotrack.track('Click-Pitch',{category:'Article-Page',label:article_num,});});$('body').on('click','.info-card.ad a',function(){article_num=$(this).parents('.full_article').attr("id");if(article_num.length==0){article_num=$(this).parents('.articorial').attr("id");}
Infotrack.track('Click-SidebarAd',{category:'Article-Page',label:article_num,});});$('body').on('click','.promoboxAd a',function(){article_num=$(this).parents('.full_article').attr("id");if(article_num.length==0){article_num=$(this).parents('.articorial').attr("id");}
Infotrack.track('Click-Promobox',{category:'Article-Page',label:article_num,});});function get_segment(){custom_dimension=$('meta[name= ResponsiveALP]').attr('content').split('_');return custom_dimension[0];}
var advertorialEnd=$('.articorial').waypoint(function(direction){Infotrack.track('View-Advertorial',{category:'Article-Page',label:$('.articorial').find('header h1').text(),});this.destroy()},{offset:'bottom-in-view'});var advertorialStart=$('.articorial').waypoint(function(direction){if(direction=="down"){Infotrack.page('marketing',{url:'https://www.fool.com'+$('.articorial').attr('data-url')})}
this.destroy()});$('body').on('click','.articorial a',function(){title=$(this).parents('.articorial').find('header h1').text();Infotrack.track('Click-Advertorial',{category:'Article-Page',label:title,});});$('body').on('click','#share-box .item',function(){Infotrack.track($(this).attr("id"),{category:'Article-Page',label:document.title,});});$('body').on('click','.full_article .left .email_report a',function(){Infotrack.track('Click-5-Stocks',{category:'Article-Page',label:'LeftCol',});});$('body').on('click','.trending-articles-section .ap-news-panel-article.trending.in-content a',function(){let itemPosition=$(".ap-news-panel-article.trending.in-content a").index($(this))+1;Infotrack.track('Click-Trending-Incontent',{category:'Article-Page',label:itemPosition,});});$('body').on('click','.read-more-section.in-content a',function(){let itemPosition=$(".read-more-section.in-content a").index($(this))+1;Infotrack.track('Click-Related-Incontent',{category:'Article-Page',label:itemPosition,});});$('body').on('click',".trending-articles-section .ap-news-panel-article.trending a:not('.ap-news-panel-article.trending.in-content a')",function(){let itemPosition=$(".ap-news-panel-article.trending a:not('.ap-news-panel-article.trending.in-content a')").index($(this))+1;Infotrack.track('Click-Trending-Sidebar',{category:'Article-Page',label:itemPosition,});});$('body').on('click','.market-performance-card .market-table a',function(){Infotrack.track('Click-'+$(this).attr('id'),{category:'Article-Page',label:'Fool returns box',});});;var adv_flag=0;$(window).on('scroll',function(){if($('.articorial').attr('data-toggle')=="True"&&document.location.pathname!=$('.articorial').attr('data-url'))
{if(adv_flag==0){url="/investing-news/content_by_path/"+$('.articorial').attr('data-url')+"?adv=1";$.ajax({url:url,type:"GET",success:function(data){$('.articorial').append(data.html);$('#article-1 .special-message').hide();$(".endless-body .articorial #pitch").each(function(){current_id=$(this).attr("id");$(this).attr("id","adv-"+current_id);});$('.endless-body .articorial #adv_text').text($('.articorial').attr('data-text'));window.postEndlessScrollArticleAdded();var pitchId=data.pitchId;window.PitchEngine.initialize({placement:'article_pitch',tickers:data.tickers,containsPitchBase:false,pitchId:pitchId,skin:'EcappedNonBuyerTemplateTest',pitchContainer:'adv-pitch',responsive:'True'});},error:function(xhr,errmsg,err){console.log(xhr.status+errmsg+err);console.log(xhr.responseText);},});}
adv_flag=1;}});;var nextArticleLink=$('#next-article');var readMore=$(".read-more-link");if(!readMore[0]&&!window.paginator_next_uri){nextArticleLink.css('display','none');}
else if(readMore[0]){nextArticleLink.attr('href',$(".read-more-link")[0].href);}
if(window.paginator_next_uri){nextArticleLink.attr('href',window.paginator_next_uri);};